### ISSUE TITLE
SteamAudio: Unity 2021 LTS segfault when using Reverb + building in Docker

### ISSUE THREAD

**Issue by jchown** [ValveSoftware/steam-audio#204]
We are using Unity Docker images from [game.ci](https://game.ci/) for building (actually, exporting native projects and then building on the target development OS). The image we are currently using is `ubuntu-2021.3.3f1-android-1.0.1`

When we try to use a reverb using SteamAudio, we get this segfault - which doesn't happen when we build manually on Windows.
```
Preloading 1 native plugins for Editor in 1.29 ms.
Caught fatal signal - signo:11 code:1 errno:0 addr:(nil)
Obtained 26 stack frames.
#0  0x00559710c0a1dc in burst_signal_handler(int, siginfo_t*, void*)
#1  0x007fd4739fc980 in funlockfile
#2  0x007fd4005e442e in ReverbEffect::setParam(UnityAudioEffectState*, int, float)
#3  0x00559711484711 in UnityAudioEffect_InternalSetFloatParameterCallback(FMOD_DSP_STATE*, int, float)
#4  0x00559713608d1e in FMOD::DSP::setParameter(int, float)
#5  0x005597114e0894 in audio::mixer::UpdateAudioMixerMemory(audio::mixer::AudioMixerConstant const&, audio::mixer::AudioMixerMemory&, float, FMOD::System*, float)
#6  0x005597114df466 in audio::mixer::CreateAudioMixerMemory(audio::mixer::AudioMixerConstant const&, FMOD::System*, RuntimeBaseAllocator&, int, bool, char const*)
#7  0x005597114a0a80 in AudioMixer::EnsureValidRuntime()
#8  0x005597114a0952 in AudioMixer::ForceUpdateInEditor()
#9  0x00559711d2677c in AudioMixerController::AwakeFromLoad(AwakeFromLoadMode)
#10 0x005597110cfd7d in AwakeFromLoadQueue::InvokePersistentManagerAwake(AwakeFromLoadQueue::Item*, unsigned int, AwakeFromLoadMode, bool)
#11 0x005597110cf344 in AwakeFromLoadQueue::PersistentManagerAwakeFromLoad(ErrorsAndWarningsCapture*, bool)
#12 0x005597110a33a3 in PersistentManager::IntegrateAllThreadedObjects()
#13 0x005597110a416b in PersistentManager::LoadAndIntegrateAllPreallocatedObjects(PersistentManager::LockFlags)
#14 0x005597110a2dfc in PersistentManager::ReadObject(int, AwakeFromLoadMode)
#15 0x005597104cae61 in PPtr<Object>::operator Object*() const
#16 0x00559710754d47 in AssetDatabase_CUSTOM_LoadMainAssetAtPath(ScriptingBackendNativeStringPtrOpaque*)
#17 0x000000407b0f03 in (wrapper managed-to-native) UnityEditor.AssetDatabase:LoadMainAssetAtPath (string)
#18 0x00000040aa0b15 in System.Linq.Enumerable/SelectManySingleSelectorIterator`2<TSource_REF, TResult_REF>:MoveNext ()
#19 0x00000040a9405f in Unity.VisualScripting.LinqUtility/<Concat>d__0`1<T_REF>:MoveNext ()
#20 0x000000406facae in Unity.VisualScripting.AotPreBuilder/<FindAllProjectStubs>d__15:MoveNext ()
#21 0x0000004157acf2 in System.Linq.Enumerable/DistinctIterator`1<TSource_REF>:MoveNext ()
#22 0x000000406f8b4c in Unity.VisualScripting.AotPreBuilder:GenerateCodeAndWriteToStream (System.Collections.Generic.IEnumerable`1<Unity.VisualScripting.AotStubWriter>,System.IO.TextWriter)
#23 0x000000406f0500 in Unity.VisualScripting.AotPreBuilder:GenerateAotStubs ()
#24 0x000000406f02f4 in Unity.VisualScripting.AotPreBuilder:OnPreprocessBuild (UnityEditor.Build.Reporting.BuildReport)
#25 0x000000406be050 in UnityEditor.Build.BuildPipelineInterfaces:OnBuildPreProcess (UnityEditor.Build.Reporting.BuildReport)
```

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0, which includes various crash fixes: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.

Try it out and let us know if these crashes persist in the new version.
